/* USER CODE BEGIN Header */
/**
  *****************************************************************************
  * @file           : can_AMS_CAN.c
  * @author         : David Hernández Rentero
  * @project        : main
  * @date           : 2026-08-27
  * @editor         : Visual Studio Code
  *
  * @brief          : CAN program body
  * @attention      : La obtención de los datos de la corriente hay que revisar
  *                   como se obtiene ya que tengo que confirmar el DBC y su 
  *                   estructura
  *****************************************************************************
  */
/* USER CODE END Header */


/* Includes ------------------------------------------------------------------*/
#include "bms/can.h"                                                                                                    // Existing BMS CAN API and error type

#include "bms/macros.h"                                                                                                 // BUBBLE_ERR and project helper macros
#include "fdcan.h"                                                                                                      // FDCAN1/FDCAN2 handles generated by CubeMX
#include "main.h"                                                                                                       // Error_Handler and common project declarations
#include "stm32g4xx_hal_conf.h"                                                                                         // STM32 HAL FDCAN definitions

#include <stdbool.h>                                                                                                    // bool, true and false
#include <stddef.h>                                                                                                     // size_t
#include <stdint.h>                                                                                                     // Fixed-width integer types

/* Private typedef -----------------------------------------------------------*/
typedef struct
{
  uint32_t identifier;                                                                                                  // 11-bit or 29-bit CAN identifier exactly as reported by the STM32 HAL
  uint32_t id_type;                                                                                                     // FDCAN_STANDARD_ID or FDCAN_EXTENDED_ID
  uint32_t data_length;                                                                                                 // STM32 HAL DLC encoding stored from FDCAN_RxHeaderTypeDef::DataLength
  uint32_t timestamp_ms;                                                                                                // HAL tick at which the frame was extracted from RX FIFO0
  uint8_t  data[8];                                                                                                     // Complete Classic-CAN payload; unused bytes remain zero
} CAN_RawFrame_t;

/* Private define ------------------------------------------------------------*/
#define CAN_RX_LOG_SIZE                       16U                                                                       // Number of raw frames retained per CAN controller for debugging/protocol identification

#define IMD_CAN_ID_INFO_GENERAL               0x037U                                                                    // Bender ISO175C DBC Standard ID: IMD_InfoGeneral
#define IMD_CAN_ID_INFO_ISOLATION_DETAIL      0x038U                                                                    // Bender ISO175C DBC Standard ID: IMD_InfoIsolationDetail
#define IMD_CAN_ID_INFO_VOLTAGE               0x039U                                                                    // Bender ISO175C DBC Standard ID: IMD_InfoVoltage
#define IMD_CAN_ID_INFO_IT_SYSTEM             0x03AU                                                                    // Bender ISO175C DBC Standard ID: IMD_InfoItSystem
#define IMD_GENERAL_MESSAGE_TIMEOUT_MS        500U                                                                      // Fail-safe timeout; set this above the configured IMD_InfoGeneral transmission period
#define IMD_DRIVE_DISABLE_PERIOD_MS           50U                                                                       // Period used to repeat Drive Enable = 0 while an IMD fault remains active

#define DTI_INVERTER_NODE_ID                  0x1BU                                                                     // DTI inverter Node ID used by the vehicle
#define DTI_PACKET_ID_DRIVE_ENABLE            0x0CU                                                                     // DTI CAN V2.4 packet ID for the Drive Enable command
#define DTI_CAN_ID_DRIVE_ENABLE               ((DTI_PACKET_ID_DRIVE_ENABLE << 8U) | DTI_INVERTER_NODE_ID)               // Extended DTI identifier: 0x0C1B for Node ID 0x1B

#define IMD_ALARM_DEVICE_ERROR                (1U << 0U)                                                                // Bender alarm bit 0: internal device error
#define IMD_ALARM_HV_POS_CONNECTION           (1U << 1U)                                                                // Bender alarm bit 1: HV positive connection error
#define IMD_ALARM_HV_NEG_CONNECTION           (1U << 2U)                                                                // Bender alarm bit 2: HV negative connection error
#define IMD_ALARM_EARTH_CONNECTION            (1U << 3U)                                                                // Bender alarm bit 3: earth connection error
#define IMD_ALARM_ISOLATION_ERROR             (1U << 4U)                                                                // Bender alarm bit 4: isolation below error threshold
#define IMD_ALARM_ISOLATION_WARNING           (1U << 5U)                                                                // Bender alarm bit 5: isolation below warning threshold
#define IMD_ALARM_ISOLATION_OUTDATED          (1U << 6U)                                                                // Bender alarm bit 6: isolation measurement exceeded its time limit
#define IMD_ALARM_UNBALANCE                   (1U << 7U)                                                                // Bender alarm bit 7: unbalance alarm
#define IMD_ALARM_UNDERVOLTAGE                (1U << 8U)                                                                // Bender alarm bit 8: undervoltage alarm
#define IMD_ALARM_UNSAFE_TO_START             (1U << 9U)                                                                // Bender alarm bit 9: unsafe-to-start condition
#define IMD_ALARM_EARTHLIFT                   (1U << 10U)                                                               // Bender alarm bit 10: earthlift opened
#define IMD_ALARM_SIGNAL_NOT_VALID            (1U << 15U)                                                               // Bender alarm bit 15: warning/alarm flags are not valid
#define IMD_ALARM_ACTIVE_MASK                 0x07FFU                                                                   // All defined active alarm/warning bits 0..10
#define IMD_ALARM_FAULT_MASK                  (IMD_ALARM_ACTIVE_MASK | IMD_ALARM_SIGNAL_NOT_VALID)                      // Every IMD alarm state that inhibits drive in this AMS implementation

#define IMD_R_ISO_STATUS_ESTIMATION           0U                                                                        // DBC value: isolation resistance is currently an estimation
#define IMD_R_ISO_STATUS_APPROXIMATION        1U                                                                        // DBC value: isolation resistance is currently an approximation
#define IMD_R_ISO_STATUS_NORMAL               2U                                                                        // DBC value: normal isolation measurement
#define IMD_R_ISO_STATUS_SNV                  3U                                                                        // DBC value: signal not valid

#define IMD_DEVICE_ACTIVITY_INITIALIZATION    0U                                                                        // DBC value: IMD initialization
#define IMD_DEVICE_ACTIVITY_NORMAL            1U                                                                        // DBC value: normal operation
#define IMD_DEVICE_ACTIVITY_SELFTEST          2U                                                                        // DBC value: self-test operation
#define IMD_DEVICE_ACTIVITY_SNV               255U                                                                      // DBC value: signal not valid

#define IMD_R_ISO_SNV_RAW                     0xFFFFU                                                                   // DBC raw value indicating that the isolation-resistance signal is not valid

#define IMD_FDCAN_HANDLE                      hfdcan2                                                                   // CAN interface physically assigned to the Standard-ID Bender IMD; change here if wiring is different
#define INVERTER_FDCAN_HANDLE                 hfdcan1                                                                   // Vehicle/inverter CAN interface used to transmit the DTI Extended-ID Drive Disable command

/* Private variables ---------------------------------------------------------*/
volatile CAN_RawFrame_t CAN1_rx_log[CAN_RX_LOG_SIZE] = {0};                                                             // Circular log containing the latest raw FDCAN1 frames
volatile CAN_RawFrame_t CAN2_rx_log[CAN_RX_LOG_SIZE] = {0};                                                             // Circular log containing the latest raw FDCAN2 frames
volatile uint32_t       CAN1_rx_count = 0U;                                                                             // Total number of data frames successfully extracted from FDCAN1 RX FIFO0
volatile uint32_t       CAN2_rx_count = 0U;                                                                             // Total number of data frames successfully extracted from FDCAN2 RX FIFO0
volatile uint32_t       CAN1_standard_count = 0U;                                                                       // Number of received FDCAN1 Standard-ID data frames
volatile uint32_t       CAN1_extended_count = 0U;                                                                       // Number of received FDCAN1 Extended-ID data frames
volatile uint32_t       CAN2_standard_count = 0U;                                                                       // Number of received FDCAN2 Standard-ID data frames
volatile uint32_t       CAN2_extended_count = 0U;                                                                       // Number of received FDCAN2 Extended-ID data frames
volatile bool           CAN_reception_error = false;                                                                    // Set when HAL cannot extract a frame that was present in RX FIFO0

volatile float          IMD_r_iso_corrected_kohm = 0.0f;                                                                // ID 0x37 bytes 0..1: corrected insulation resistance in kOhm
volatile uint8_t        IMD_r_iso_status = IMD_R_ISO_STATUS_SNV;                                                        // ID 0x37 bits 16..17: estimation/approximation/normal/SNV status
volatile uint8_t        IMD_isolation_counter = 0U;                                                                     // ID 0x37 byte 3: isolation measurement counter
volatile uint16_t       IMD_alarm_flags = IMD_ALARM_SIGNAL_NOT_VALID;                                                   // ID 0x37 bytes 4..5: complete warning/alarm bit field
volatile uint8_t        IMD_device_activity = IMD_DEVICE_ACTIVITY_SNV;                                                  // ID 0x37 byte 6: initialization/normal/self-test/SNV state

volatile bool           IMD_alarm_device_error = false;                                                                 // Decoded alarm bit 0
volatile bool           IMD_alarm_hv_pos_connection = false;                                                            // Decoded alarm bit 1
volatile bool           IMD_alarm_hv_neg_connection = false;                                                            // Decoded alarm bit 2
volatile bool           IMD_alarm_earth_connection = false;                                                             // Decoded alarm bit 3
volatile bool           IMD_alarm_isolation_error = false;                                                              // Decoded alarm bit 4
volatile bool           IMD_alarm_isolation_warning = false;                                                            // Decoded alarm bit 5
volatile bool           IMD_alarm_isolation_outdated = false;                                                           // Decoded alarm bit 6
volatile bool           IMD_alarm_unbalance = false;                                                                    // Decoded alarm bit 7
volatile bool           IMD_alarm_undervoltage = false;                                                                 // Decoded alarm bit 8
volatile bool           IMD_alarm_unsafe_to_start = false;                                                              // Decoded alarm bit 9
volatile bool           IMD_alarm_earthlift = false;                                                                    // Decoded alarm bit 10
volatile bool           IMD_alarm_signal_not_valid = true;                                                              // Decoded alarm bit 15; true means the alarm field itself is invalid

volatile float          IMD_r_iso_neg_kohm = 0.0f;                                                                      // ID 0x38 bytes 0..1: insulation resistance from HV- to earth
volatile float          IMD_r_iso_pos_kohm = 0.0f;                                                                      // ID 0x38 bytes 2..3: insulation resistance from HV+ to earth
volatile float          IMD_r_iso_original_kohm = 0.0f;                                                                 // ID 0x38 bytes 4..5: original non-corrected isolation resistance
volatile uint8_t        IMD_isolation_detail_counter = 0U;                                                              // ID 0x38 byte 6: detailed isolation measurement counter
volatile uint8_t        IMD_isolation_quality_percent = 0U;                                                             // ID 0x38 byte 7: isolation measurement quality in percent

volatile float          IMD_hv_voltage_v = 0.0f;                                                                        // ID 0x39 bytes 0..1: complete HV-system voltage
volatile float          IMD_hv_neg_to_earth_v = 0.0f;                                                                   // ID 0x39 bytes 2..3: HV- potential relative to earth
volatile float          IMD_hv_pos_to_earth_v = 0.0f;                                                                   // ID 0x39 bytes 4..5: HV+ potential relative to earth
volatile uint8_t        IMD_voltage_counter = 0U;                                                                       // ID 0x39 byte 6: voltage measurement counter

volatile float          IMD_capacity_uF = 0.0f;                                                                         // ID 0x3A bytes 0..1: measured IT-system capacity in microfarads
volatile uint8_t        IMD_capacity_counter = 0U;                                                                      // ID 0x3A byte 2: capacity measurement counter
volatile uint8_t        IMD_unbalance_percent = 0U;                                                                     // ID 0x3A byte 3: measured unbalance percentage
volatile uint8_t        IMD_unbalance_counter = 0U;                                                                     // ID 0x3A byte 4: unbalance measurement counter
volatile float          IMD_hv_frequency_hz = 0.0f;                                                                     // ID 0x3A bytes 5..6: measured HV frequency

volatile bool           IMD_info_general_received = false;                                                              // True after receiving one complete 0x37 Standard-ID frame
volatile bool           IMD_info_isolation_received = false;                                                            // True after receiving one complete 0x38 Standard-ID frame
volatile bool           IMD_info_voltage_received = false;                                                              // True after receiving one complete 0x39 Standard-ID frame
volatile bool           IMD_info_it_system_received = false;                                                            // True after receiving one complete 0x3A Standard-ID frame
volatile uint32_t       IMD_last_general_tick = 0U;                                                                     // Tick of the latest complete IMD_InfoGeneral frame
volatile uint32_t       IMD_last_isolation_tick = 0U;                                                                   // Tick of the latest complete IMD_InfoIsolationDetail frame
volatile uint32_t       IMD_last_voltage_tick = 0U;                                                                     // Tick of the latest complete IMD_InfoVoltage frame
volatile uint32_t       IMD_last_it_system_tick = 0U;                                                                   // Tick of the latest complete IMD_InfoItSystem frame

volatile bool           IMD_communication_timeout = true;                                                               // Fail-safe condition: no valid periodic general IMD status is currently available
volatile bool           IMD_measurement_invalid = true;                                                                 // True when R_iso status or corrected R_iso is SNV
volatile bool           IMD_device_not_normal = true;                                                                   // True while the IMD is not reporting normal operation
volatile bool           IMD_fault_active = true;                                                                        // Master safety flag; initialized true so drive is inhibited until a healthy IMD frame is received
volatile bool           IMD_drive_disable_tx_error = false;                                                             // Set when the AMS cannot queue the DTI Drive Disable frame
volatile uint32_t       IMD_drive_disable_tx_count = 0U;                                                                // Number of Drive Disable frames successfully queued because of IMD safety state

extern volatile float    AMS_battery_current;                                                                           // Physical battery current stored by main.c once the current-sensor protocol is known
extern volatile bool     AMS_current_valid;                                                                             // Indicates that AMS_battery_current contains a decoded current measurement
extern volatile uint32_t AMS_last_current_tick;                                                                         // Tick of the most recent valid current measurement

static bool              can1_started = false;                                                                          // Prevent multiple HAL_FDCAN_Start calls when bms_setup() is repeated
static bool              can2_started = false;                                                                          // Prevent multiple HAL_FDCAN_Start calls when bms_setup() is repeated
static bool              imd_drive_disable_sent_once = false;                                                           // Allows an immediate Drive Disable on every transition into an IMD fault condition
static uint32_t          imd_last_drive_disable_tick = 0U;                                                              // Tick used to repeat Drive Disable while IMD_fault_active remains true

/* Private function prototypes -----------------------------------------------*/
HAL_StatusTypeDef can_send_frame(FDCAN_HandleTypeDef *hfdcan, uint32_t id, uint32_t id_type,
                                 const uint8_t *data, uint32_t data_length);                                            // Generic Standard/Extended Classic-CAN transmitter
static void can_store_raw_frame(FDCAN_HandleTypeDef *hfdcan,
                                const FDCAN_RxHeaderTypeDef *header,
                                const uint8_t *data);                                                                   // Stores every received Standard/Extended frame in the corresponding circular buffer
static void can_receive_fifo0(FDCAN_HandleTypeDef *hfdcan);                                                             // Drains RX FIFO0 for one CAN controller
static bool can_try_decode_current_sensor(const FDCAN_RxHeaderTypeDef *header,
                                          const uint8_t *data,
                                          float *current_a);                                                            // Single hook to complete when the current-sensor CAN protocol is available
static void imd_process_frame(const FDCAN_RxHeaderTypeDef *header, const uint8_t *data);                                // Decodes the four periodic Bender ISO175C Standard-ID information frames
static void imd_decode_info_general(const uint8_t *data);                                                               // Decodes IMD_InfoGeneral, including every alarm used for safety shutdown
static void imd_decode_info_isolation_detail(const uint8_t *data);                                                      // Decodes IMD_InfoIsolationDetail
static void imd_decode_info_voltage(const uint8_t *data);                                                               // Decodes IMD_InfoVoltage
static void imd_decode_info_it_system(const uint8_t *data);                                                             // Decodes IMD_InfoItSystem
static void imd_update_fault_state(void);                                                                               // Recomputes the fail-safe IMD master fault flag
static void imd_safety_service(void);                                                                                   // Repeats the DTI Drive Disable command while an IMD fault is active
static HAL_StatusTypeDef imd_send_drive_disable(void);                                                                  // Sends Drive Enable = 0 to DTI inverter Node ID 0x1B
static uint16_t read_le_u16(const uint8_t *data);                                                                       // Reconstructs one Intel/Little-Endian unsigned 16-bit DBC value
static inline error can_send_raw(uint32_t id, const uint8_t *data,
                                 uint32_t raw_length);                                                                  // Preserves the original two-byte Standard-ID can_send() behavior

/* Private user code ---------------------------------------------------------*/

/* CAN setup -----------------------------------------------------------------*/
error can_setup(void)                                                                                                   // Starts both CAN peripherals while preserving the filters configured by MX_FDCANx_Init()
{
  TRACE("--> [BEGIN] CAN Setup\n");                                                                                     // Mark the beginning of CAN setup in the diagnostic trace
  int err = 0;                                                                                                          // Aggregate setup failures using the original project error convention

  if (!can1_started)                                                                                                    // Start FDCAN1 only once
  {
    TRACE("---> CAN1 Start\n");                                                                                         // Trace the FDCAN1 start operation
    const HAL_StatusTypeDef can1_status = HAL_FDCAN_Start(&hfdcan1);                                                    // Start FDCAN1 without DeInit/Init so its global filter is preserved
    BUBBLE_ERR(err, ERROR_CAN_TX * (can1_status != HAL_OK));                                                            // Convert the HAL result to the existing BMS CAN error representation
    if (can1_status == HAL_OK)                                                                                          // Mark the peripheral as started only if HAL accepted the request
    {
      can1_started = true;                                                                                              // Prevent a second HAL_FDCAN_Start call on FDCAN1
    }
  }

  if (!can2_started)                                                                                                    // Start FDCAN2 only once
  {
    TRACE("---> CAN2 Start\n");                                                                                         // Trace the FDCAN2 start operation
    const HAL_StatusTypeDef can2_status = HAL_FDCAN_Start(&hfdcan2);                                                    // Start FDCAN2 without DeInit/Init so its global filter is preserved
    BUBBLE_ERR(err, ERROR_CAN_TX * (can2_status != HAL_OK));                                                            // Convert the HAL result to the existing BMS CAN error representation
    if (can2_status == HAL_OK)                                                                                          // Mark the peripheral as started only if HAL accepted the request
    {
      can2_started = true;                                                                                              // Prevent a second HAL_FDCAN_Start call on FDCAN2
    }
  }

  TRACE("<-- [ END ] CAN Setup\n");                                                                                     // Mark the end of CAN setup in the diagnostic trace
  return err;                                                                                                           // Return the aggregate BMS CAN error code
}


/* CAN reception -------------------------------------------------------------*/
void can_receive_all(void)                                                                                              // Polls both CAN peripherals so no additional FDCAN IRQ handler file is required
{
  can_receive_fifo0(&hfdcan1);                                                                                          // Drain every message currently queued by FDCAN1
  can_receive_fifo0(&hfdcan2);                                                                                          // Drain every message currently queued by FDCAN2
  imd_safety_service();                                                                                                 // Apply IMD timeout supervision and repeatedly force Drive Enable = 0 whenever required
}

static void can_receive_fifo0(FDCAN_HandleTypeDef *hfdcan)                                                              // Extracts all pending Classic-CAN data frames from one RX FIFO0
{
  FDCAN_RxHeaderTypeDef header = {0};                                                                                   // Local header prevents cross-bus data races and keeps each frame self-contained
  uint8_t data[8] = {0U};                                                                                               // Local payload buffer for one Classic-CAN frame

  while (HAL_FDCAN_GetRxFifoFillLevel(hfdcan, FDCAN_RX_FIFO0) > 0U)                                                     // Continue until RX FIFO0 is completely empty
  {
    for (size_t i = 0U; i < sizeof(data); ++i)                                                                          // Clear the payload before each read because a frame can contain fewer than eight bytes
    {
      data[i] = 0U;                                                                                                     // Keep unused bytes deterministic in the raw frame log
    }

    if (HAL_FDCAN_GetRxMessage(hfdcan, FDCAN_RX_FIFO0, &header, data) != HAL_OK)                                        // Extract the oldest frame currently stored in RX FIFO0
    {
      CAN_reception_error = true;                                                                                       // Record the fault so it can be inspected by the debugger or higher-level logic
      return;                                                                                                           // Leave this FIFO to avoid repeatedly failing on the same HAL condition
    }

    if ((header.RxFrameType != FDCAN_DATA_FRAME) || (header.FDFormat != FDCAN_CLASSIC_CAN))                             // Ignore remote frames and CAN-FD frames in this Classic-CAN AMS network
    {
      continue;                                                                                                         // Process the next RX FIFO0 entry without storing an unsupported frame type
    }

    can_store_raw_frame(hfdcan, &header, data);                                                                         // Store ID type, identifier, DLC, timestamp and payload for Standard or Extended frames

    if (hfdcan == &IMD_FDCAN_HANDLE)                                                                                    // Decode Bender frames only on the CAN interface physically assigned to the IMD
    {
      imd_process_frame(&header, data);                                                                                 // Decode 0x37..0x3A when the received frame belongs to the ISO175C
    }

    float decoded_current_a = 0.0f;                                                                                     // Temporary destination used only when the current-sensor decoder recognizes the frame
    if (can_try_decode_current_sensor(&header, data, &decoded_current_a))                                               // Try every received frame because the current sensor ID/type is not known yet
    {
      AMS_battery_current = decoded_current_a;                                                                          // Store the physical current after a future protocol-specific decoder succeeds
      AMS_current_valid = true;                                                                                         // Allow 0x701B transmission only after the sensor protocol has produced a valid measurement
      AMS_last_current_tick = HAL_GetTick();                                                                            // Timestamp the decoded current value for future timeout supervision
    }
  }
}


/* CAN raw-frame storage -----------------------------------------------------*/
static void can_store_raw_frame(FDCAN_HandleTypeDef *hfdcan,
                                const FDCAN_RxHeaderTypeDef *header,
                                const uint8_t *data)                                                                    // Saves a raw frame so IMD/current-sensor traffic can be identified before every protocol is fixed
{
  volatile CAN_RawFrame_t *entry = NULL;                                                                                // Destination slot selected from the FDCAN1 or FDCAN2 circular log
  uint32_t absolute_count = 0U;                                                                                         // Total frame count before incrementing; also selects the circular-buffer index

  if (hfdcan->Instance == FDCAN1)                                                                                       // Route an FDCAN1 frame to the first raw-frame log
  {
    absolute_count = CAN1_rx_count++;                                                                                   // Count the frame and preserve the pre-increment value for the ring index
    entry = &CAN1_rx_log[absolute_count % CAN_RX_LOG_SIZE];                                                             // Select the next FDCAN1 circular-buffer slot

    if (header->IdType == FDCAN_STANDARD_ID)                                                                            // Count Standard-ID traffic independently
    {
      ++CAN1_standard_count;                                                                                            // Increment the FDCAN1 Standard-ID frame counter
    }
    else if (header->IdType == FDCAN_EXTENDED_ID)                                                                       // Count Extended-ID traffic independently
    {
      ++CAN1_extended_count;                                                                                            // Increment the FDCAN1 Extended-ID frame counter
    }
  }
  else if (hfdcan->Instance == FDCAN2)                                                                                  // Route an FDCAN2 frame to the second raw-frame log
  {
    absolute_count = CAN2_rx_count++;                                                                                   // Count the frame and preserve the pre-increment value for the ring index
    entry = &CAN2_rx_log[absolute_count % CAN_RX_LOG_SIZE];                                                             // Select the next FDCAN2 circular-buffer slot

    if (header->IdType == FDCAN_STANDARD_ID)                                                                            // Count Standard-ID traffic independently
    {
      ++CAN2_standard_count;                                                                                            // Increment the FDCAN2 Standard-ID frame counter
    }
    else if (header->IdType == FDCAN_EXTENDED_ID)                                                                       // Count Extended-ID traffic independently
    {
      ++CAN2_extended_count;                                                                                            // Increment the FDCAN2 Extended-ID frame counter
    }
  }
  else                                                                                                                  // Reject handles that are neither FDCAN1 nor FDCAN2
  {
    return;                                                                                                             // Leave without touching either log
  }

  entry->identifier = header->Identifier;                                                                               // Store the complete 11-bit or 29-bit identifier
  entry->id_type = header->IdType;                                                                                      // Store whether the identifier was Standard or Extended
  entry->data_length = header->DataLength;                                                                              // Store the HAL DLC field exactly as received
  entry->timestamp_ms = HAL_GetTick();                                                                                  // Store the reception time in milliseconds

  for (size_t i = 0U; i < 8U; ++i)                                                                                      // Copy all eight bytes so the frame can be inspected later
  {
    entry->data[i] = data[i];                                                                                           // Copy one payload byte into the selected circular-buffer entry
  }
}


/* IMD frame decoding --------------------------------------------------------*/
static void imd_process_frame(const FDCAN_RxHeaderTypeDef *header, const uint8_t *data)                                 // Identifies and decodes Bender ISO175C periodic messages from its DBC
{
  if ((header->IdType != FDCAN_STANDARD_ID) || (header->DataLength != FDCAN_DLC_BYTES_8))                               // The supplied Bender DBC defines these periodic messages as 8-byte Standard-ID frames
  {
    return;                                                                                                             // Do not refresh IMD safety timestamps with malformed or Extended-ID traffic
  }

  switch (header->Identifier)                                                                                           // Select the DBC message by its 11-bit identifier
  {
    case IMD_CAN_ID_INFO_GENERAL:                                                                                       // 0x37 / 55 decimal: isolation status, alarms and device activity
      imd_decode_info_general(data);                                                                                    // Decode the safety-critical general information frame
      break;                                                                                                            // Finish processing this IMD frame

    case IMD_CAN_ID_INFO_ISOLATION_DETAIL:                                                                              // 0x38 / 56 decimal: detailed isolation resistances and quality
      imd_decode_info_isolation_detail(data);                                                                           // Decode detailed isolation measurements
      break;                                                                                                            // Finish processing this IMD frame

    case IMD_CAN_ID_INFO_VOLTAGE:                                                                                       // 0x39 / 57 decimal: HV system and HV-to-earth voltages
      imd_decode_info_voltage(data);                                                                                    // Decode the three voltage measurements
      break;                                                                                                            // Finish processing this IMD frame

    case IMD_CAN_ID_INFO_IT_SYSTEM:                                                                                     // 0x3A / 58 decimal: capacity, unbalance and HV frequency
      imd_decode_info_it_system(data);                                                                                  // Decode the IT-system information frame
      break;                                                                                                            // Finish processing this IMD frame

    default:                                                                                                            // Standard-ID frame not belonging to the four periodic Bender messages
      break;                                                                                                            // Keep it only in the raw CAN log
  }
}

static void imd_decode_info_general(const uint8_t *data)                                                                // Decodes Bender DBC message IMD_InfoGeneral, Standard ID 0x37
{
  const uint16_t r_iso_raw = read_le_u16(&data[0]);                                                                     // Bits 0..15 @1+: corrected isolation resistance, Intel/Little-Endian
  const uint16_t alarm_raw = read_le_u16(&data[4]);                                                                     // Bits 32..47 @1+: warning/alarm field, Intel/Little-Endian

  IMD_r_iso_corrected_kohm = (float)r_iso_raw;                                                                          // Factor 1, offset 0: raw value directly represents kOhm
  IMD_r_iso_status = (uint8_t)(data[2] & 0x03U);                                                                        // Bits 16..17: two-bit R_iso measurement status
  IMD_isolation_counter = data[3];                                                                                      // Bits 24..31: isolation measurement counter
  IMD_alarm_flags = alarm_raw;                                                                                          // Preserve the complete 16-bit warning/alarm field for diagnostics
  IMD_device_activity = data[6];                                                                                        // Bits 48..55: IMD device activity

  IMD_alarm_device_error = (alarm_raw & IMD_ALARM_DEVICE_ERROR) != 0U;                                                  // Bit 0: internal device error
  IMD_alarm_hv_pos_connection = (alarm_raw & IMD_ALARM_HV_POS_CONNECTION) != 0U;                                        // Bit 1: HV+ connection error
  IMD_alarm_hv_neg_connection = (alarm_raw & IMD_ALARM_HV_NEG_CONNECTION) != 0U;                                        // Bit 2: HV- connection error
  IMD_alarm_earth_connection = (alarm_raw & IMD_ALARM_EARTH_CONNECTION) != 0U;                                          // Bit 3: earth connection error
  IMD_alarm_isolation_error = (alarm_raw & IMD_ALARM_ISOLATION_ERROR) != 0U;                                            // Bit 4: isolation below the error threshold
  IMD_alarm_isolation_warning = (alarm_raw & IMD_ALARM_ISOLATION_WARNING) != 0U;                                        // Bit 5: isolation below the warning threshold
  IMD_alarm_isolation_outdated = (alarm_raw & IMD_ALARM_ISOLATION_OUTDATED) != 0U;                                      // Bit 6: measurement exceeds its configured time limit
  IMD_alarm_unbalance = (alarm_raw & IMD_ALARM_UNBALANCE) != 0U;                                                        // Bit 7: unbalance alarm
  IMD_alarm_undervoltage = (alarm_raw & IMD_ALARM_UNDERVOLTAGE) != 0U;                                                  // Bit 8: undervoltage alarm
  IMD_alarm_unsafe_to_start = (alarm_raw & IMD_ALARM_UNSAFE_TO_START) != 0U;                                            // Bit 9: unsafe-to-start condition
  IMD_alarm_earthlift = (alarm_raw & IMD_ALARM_EARTHLIFT) != 0U;                                                        // Bit 10: earthlift opened
  IMD_alarm_signal_not_valid = (alarm_raw & IMD_ALARM_SIGNAL_NOT_VALID) != 0U;                                          // Bit 15: all warning/alarm flags are invalid

  IMD_info_general_received = true;                                                                                     // Record that at least one complete periodic general frame has arrived
  IMD_last_general_tick = HAL_GetTick();                                                                                // Refresh the communication watchdog only with a correctly formed 0x37 frame

  IMD_measurement_invalid = (IMD_r_iso_status == IMD_R_ISO_STATUS_SNV) || (r_iso_raw == IMD_R_ISO_SNV_RAW);             // Treat any DBC SNV indication as unsafe for drive
  IMD_device_not_normal = IMD_device_activity != IMD_DEVICE_ACTIVITY_NORMAL;                                            // Initialization, self-test, SNV or unknown values inhibit drive

  imd_update_fault_state();                                                                                             // Immediately update the master fault flag so the next safety service sends Drive Disable
}

static void imd_decode_info_isolation_detail(const uint8_t *data)                                                       // Decodes Bender DBC message IMD_InfoIsolationDetail, Standard ID 0x38
{
  IMD_r_iso_neg_kohm = (float)read_le_u16(&data[0]);                                                                    // Bytes 0..1: R_iso_neg, factor 1 kOhm/bit
  IMD_r_iso_pos_kohm = (float)read_le_u16(&data[2]);                                                                    // Bytes 2..3: R_iso_pos, factor 1 kOhm/bit
  IMD_r_iso_original_kohm = (float)read_le_u16(&data[4]);                                                               // Bytes 4..5: original R_iso, factor 1 kOhm/bit
  IMD_isolation_detail_counter = data[6];                                                                               // Byte 6: detailed isolation measurement counter
  IMD_isolation_quality_percent = data[7];                                                                              // Byte 7: isolation measurement quality percentage
  IMD_info_isolation_received = true;                                                                                   // Mark the detailed-isolation frame as available
  IMD_last_isolation_tick = HAL_GetTick();                                                                              // Timestamp the latest detailed-isolation frame
}

static void imd_decode_info_voltage(const uint8_t *data)                                                                // Decodes Bender DBC message IMD_InfoVoltage, Standard ID 0x39
{
  IMD_hv_voltage_v = ((float)read_le_u16(&data[0]) * 0.05f) - 1606.0f;                                                  // Bytes 0..1: HV-system voltage, factor 0.05 V/bit and offset -1606 V
  IMD_hv_neg_to_earth_v = ((float)read_le_u16(&data[2]) * 0.05f) - 1606.0f;                                             // Bytes 2..3: HV- to earth voltage with the same DBC conversion
  IMD_hv_pos_to_earth_v = ((float)read_le_u16(&data[4]) * 0.05f) - 1606.0f;                                             // Bytes 4..5: HV+ to earth voltage with the same DBC conversion
  IMD_voltage_counter = data[6];                                                                                        // Byte 6: voltage measurement counter
  IMD_info_voltage_received = true;                                                                                     // Mark the voltage information frame as available
  IMD_last_voltage_tick = HAL_GetTick();                                                                                // Timestamp the latest IMD voltage frame
}

static void imd_decode_info_it_system(const uint8_t *data)                                                              // Decodes Bender DBC message IMD_InfoItSystem, Standard ID 0x3A
{
  IMD_capacity_uF = (float)read_le_u16(&data[0]) * 0.1f;                                                                // Bytes 0..1: IT-system capacity, factor 0.1 uF/bit
  IMD_capacity_counter = data[2];                                                                                       // Byte 2: capacity measurement counter
  IMD_unbalance_percent = data[3];                                                                                      // Byte 3: measured unbalance percentage
  IMD_unbalance_counter = data[4];                                                                                      // Byte 4: unbalance measurement counter
  IMD_hv_frequency_hz = (float)read_le_u16(&data[5]) * 0.0078f;                                                         // Bytes 5..6: HV frequency using the factor defined by the supplied DBC
  IMD_info_it_system_received = true;                                                                                   // Mark the IT-system information frame as available
  IMD_last_it_system_tick = HAL_GetTick();                                                                              // Timestamp the latest IT-system information frame
}


/* IMD safety and Drive Disable ---------------------------------------------*/
static void imd_update_fault_state(void)                                                                                // Combines communication, DBC validity, device state and all defined alarm bits into one safety decision
{
  const uint32_t now = HAL_GetTick();                                                                                   // Read the current system tick once for a coherent timeout calculation
  const bool alarm_active = (IMD_alarm_flags & IMD_ALARM_FAULT_MASK) != 0U;                                             // Any Bender alarm/warning bit 0..10 or alarm-SNV bit 15 inhibits drive

  IMD_communication_timeout = !IMD_info_general_received ||                                                             // Before the first 0x37 frame the IMD state is unknown and therefore unsafe
                              ((uint32_t)(now - IMD_last_general_tick) > IMD_GENERAL_MESSAGE_TIMEOUT_MS);               // A stale general-status frame is treated as loss of IMD supervision
  IMD_fault_active = IMD_communication_timeout ||                                                                       // Communication loss or missing initial status forces the safe state
                     IMD_measurement_invalid ||                                                                         // Invalid R_iso status/value forces the safe state
                     IMD_device_not_normal ||                                                                           // Initialization, self-test, SNV or unknown device state forces the safe state
                     alarm_active;                                                                                      // Any defined Bender alarm/warning forces the safe state requested for the AMS
}

static void imd_safety_service(void)                                                                                    // Continuously enforces Drive Disable while IMD_fault_active is true
{
  const uint32_t now = HAL_GetTick();                                                                                   // Read the current tick once for fault timeout and command timing
  const bool fault_was_active = IMD_fault_active;                                                                       // Preserve the previous state so a new fault can trigger an immediate command

  imd_update_fault_state();                                                                                             // Re-evaluate communication timeout even when no new IMD frame has arrived

  if (!IMD_fault_active)                                                                                                // Healthy IMD means this AMS no longer needs to force the inverter disabled
  {
    imd_drive_disable_sent_once = false;                                                                                // Arm an immediate Drive Disable if a new IMD fault appears later
    return;                                                                                                             // Do not send Drive Enable = 1; re-enabling remains the responsibility of the normal vehicle control logic
  }

  if (!fault_was_active)                                                                                                // A new fault has just appeared since the previous service call
  {
    imd_drive_disable_sent_once = false;                                                                                // Force immediate transmission instead of waiting for the periodic 50 ms interval
  }

  if (!imd_drive_disable_sent_once ||                                                                                   // Always transmit immediately on startup/new fault
      ((uint32_t)(now - imd_last_drive_disable_tick) >= IMD_DRIVE_DISABLE_PERIOD_MS))                                   // Then repeat Drive Disable periodically while the fault persists
  {
    if (imd_send_drive_disable() == HAL_OK)                                                                             // Queue the DTI command on the inverter CAN interface
    {
      IMD_drive_disable_tx_error = false;                                                                               // Clear an earlier transmission-error indication after a successful queue operation
      ++IMD_drive_disable_tx_count;                                                                                     // Count successful safety commands for diagnostics
      imd_drive_disable_sent_once = true;                                                                               // Record that at least one disable command has been sent for the current fault
      imd_last_drive_disable_tick = now;                                                                                // Start the repeat interval from this successful transmission
    }
    else                                                                                                                // HAL could not queue the safety command
    {
      IMD_drive_disable_tx_error = true;                                                                                // Preserve the transmission failure for debugger/higher-level supervision
    }
  }
}

static HAL_StatusTypeDef imd_send_drive_disable(void)                                                                   // Sends the DTI V2.4 Drive Enable command with physical value 0 = Drive not allowed
{
  const uint8_t tx_data[8] = {                                                                                          // DTI allows an 8-byte frame with unused bytes filled with 0xFF
      0x00U,                                                                                                            // Byte 0: Drive Enable = 0 -> Drive not allowed
      0xFFU, 0xFFU, 0xFFU, 0xFFU, 0xFFU, 0xFFU, 0xFFU                                                                   // Bytes 1..7: not used by the Drive Enable command
  };

  return can_send_frame(&INVERTER_FDCAN_HANDLE, DTI_CAN_ID_DRIVE_ENABLE, FDCAN_EXTENDED_ID,
                        tx_data, FDCAN_DLC_BYTES_8);                                                                    // Send Extended ID 0x0C1B to DTI inverter Node ID 0x1B
}


/* CAN data-conversion helpers ----------------------------------------------*/
static uint16_t read_le_u16(const uint8_t *data)                                                                        // Reconstructs the @1+ Intel/Little-Endian 16-bit signals used in the Bender DBC
{
  return (uint16_t)data[0] | ((uint16_t)data[1] << 8U);                                                                 // Byte 0 contains bits 7..0 and byte 1 contains bits 15..8
}

#pragma region lectura corriente
/* Current sensor decoding --------------------------------------------------*/
static bool can_try_decode_current_sensor(const FDCAN_RxHeaderTypeDef *header,
                                          const uint8_t *data,
                                          float *current_a)                                                             // Protocol-specific current decoder intentionally left inactive until the sensor manual is known
{
  (void)header;                                                                                                         // Suppress unused-parameter warnings while no current-sensor identifier/format is available
  (void)data;                                                                                                           // Suppress unused-parameter warnings while no payload definition is available
  (void)current_a;                                                                                                      // Suppress unused-parameter warnings while no physical-current conversion is available

  /* TODO CURRENT SENSOR:
   * 1. Check header->IdType once the sensor is known (Standard or Extended).
   * 2. Check header->Identifier against the sensor message ID.
   * 3. Reconstruct the raw current value using the documented byte order/sign.
   * 4. Apply the documented scale/offset and write the result to *current_a.
   * 5. Return true only after all checks pass.
   *
   * Until those data are known, every frame is still retained in CAN1_rx_log/CAN2_rx_log,
   * but no arbitrary CAN frame is allowed to become AMS_battery_current.
   */
  return false;                                                                                                         // Keep AMS_current_valid false until the real sensor protocol is implemented
}
#pragma end region

/* CAN transmission ---------------------------------------------------------*/
HAL_StatusTypeDef can_send_frame(FDCAN_HandleTypeDef *hfdcan, uint32_t id, uint32_t id_type,
                                 const uint8_t *data, uint32_t data_length)                                             // Sends one Classic-CAN frame with caller-selected Standard or Extended ID
{
  if ((hfdcan == NULL) || (data == NULL))                                                                               // Reject invalid pointers before calling the HAL
  {
    return HAL_ERROR;                                                                                                   // Report invalid arguments to the caller
  }

  if ((id_type != FDCAN_STANDARD_ID) && (id_type != FDCAN_EXTENDED_ID))                                                 // Accept only the two Classic-CAN identifier formats
  {
    return HAL_ERROR;                                                                                                   // Reject unsupported identifier-type values
  }

  FDCAN_TxHeaderTypeDef header = {                                                                                      // Build the STM32 HAL transmit header for one Classic-CAN data frame
      .Identifier = id,                                                                                                 // Use the caller-provided 11-bit or 29-bit identifier
      .IdType = id_type,                                                                                                // Preserve Standard or Extended format selected by the caller
      .TxFrameType = FDCAN_DATA_FRAME,                                                                                  // Transmit a data frame rather than a remote frame
      .DataLength = data_length,                                                                                        // Use the STM32 HAL DLC constant provided by the caller
      .ErrorStateIndicator = FDCAN_ESI_ACTIVE,                                                                          // Report the controller as error active during normal operation
      .BitRateSwitch = FDCAN_BRS_OFF,                                                                                   // Classic CAN does not use CAN-FD bit-rate switching
      .FDFormat = FDCAN_CLASSIC_CAN,                                                                                    // Force Classic CAN rather than CAN FD
      .TxEventFifoControl = FDCAN_NO_TX_EVENTS,                                                                         // No transmit-event FIFO entry is required for these AMS messages
      .MessageMarker = 0U,                                                                                              // No application message marker is required
  };

  return HAL_FDCAN_AddMessageToTxFifoQ(hfdcan, &header, data);                                                          // Queue the prepared frame in the selected FDCAN transmit FIFO
}

static inline error can_send_raw(uint32_t id, const uint8_t *data,
                                 uint32_t raw_length)                                                                   // Legacy sender retained for existing BMS modules that call can_send()
{
  return ERROR_CAN_TX * (can_send_frame(&FDCAN_HANDLE, id, FDCAN_STANDARD_ID,
                                        data, raw_length) != HAL_OK);                                                   // Preserve the original Standard-ID behavior of can_send()
}

// NOLINTNEXTLINE (bugprone-easily-swappable-parameters)
error can_send(uint32_t const id, uint16_t const data)                                                                  // Legacy two-byte Standard-ID API retained for backward compatibility
{
  uint8_t data_bytes[2] = {                                                                                             // Explicit byte array avoids depending on MCU memory endianness
      (uint8_t)data,                                                                                                    // Original implementation sends the low byte first
      (uint8_t)(data >> 8U),                                                                                            // Original implementation sends the high byte second
  };

  return can_send_raw(id, data_bytes, FDCAN_DLC_BYTES_2);                                                               // Send the legacy two-byte frame through the configured BMS CAN handle
}
