[package]
name = "BMS-Monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.36.1", features = ["persistence"] }
egui_plot = "0.37.0"
enum_dispatch = "0.3.13"
fixedbitset = "0.5.7"
ordered-float = "5.5.0"
parking_lot = "0.12.5"
serde = "1.0.229"
serialport = { version = "4.9.0", features = ["serde"] }
